#:schema ./resume.schema.json

[profile]
first_name = "Andrew"
middle_name = "Jordan"
last_name = "Leung"

[contact]
personal_email = "andrewleung104@gmail.com"
work_email = "andleung@paypal.com"
phone = "9782218810"

[[education]]
institution = "Northeastern University"
when = { Range = { start = 2017-09-01, end = 2022-05-01 } }
location = { CityState = ["Boston", "MA"] }
area = "Computer Science"
kind = "B.S."
score = "3.9/4.0"  # 3.913
url = "https://www.northeastern.edu"

[[socials]]
network = "personal"
url = "https://andrewjleung.me"

[[socials]]
network = "GitHub"
username = "andrewjleung"
url = "https://github.com/andrewjleung"

[[socials]]
network = "LinkedIn"
username = "andrewjleung-"
url = "https://linkedin.com/in/andrewjleung-"

[skills]
Languages = [
  "TypeScript",
  "JavaScript",
  "Ruby",
  "Rust",
  "Go",
  "Python",
  "SQL",
  "HTML",
  "CSS",
]
Tooling = [
  "React",
  "Next.js",
  "Tailwind",
  "Ruby on Rails",
  "RSpec",
  "PostgreSQL",
  "Google BigQuery",
  "Git",
  "Neovim",
]

[[experiences]]
kind = "work"
name = "Software Engineer"
context = "PayPal"
location = "Remote"
when = { Started = 2023-06-12 }
highlights = [
  "Maintained Braintree's Ruby on Rails app used to payout $1.6B a day across 15K merchants",
  "Led development, coordinated live testing, and served as a subject matter expert for a feature used to withhold $1.4M a day from high-risk or delinquent merchants",
  "Automated a $57M migration in held funds to new banking partners and an updated internal ledger",
  "Coordinated engineering effort to debug and resolve funds reconciliation issues, decreasing unreconciled funds by 88% and increasing reconciliation accuracy to 99.7%",
  "Identified and patched a regression caused by a Rails upgrade, correcting the misallocation of $80M",
  "Increased monthly revenue by $650K by correcting fee calculations to round instead of truncate",
  # "Prevented the misallocation of $6M by identifying and fixing an edge case in the timing of internal routing of funds to different bank accounts",
  # "Interviewed intern candidates and onboarded engineers with knowledge sharing and pair programming",
]

[[experiences]]
kind = "work"
name = "Software Engineer Co-op"
context = "Poloniex"
location = "Remote"
when = { Range = { start = 2021-01-01, end = 2021-08-01 } }
highlights = [
  "Integrated Poloniex's web app with a CMS, saving hours of weekly engineering effort spent manually updating web content on behalf of marketing teams",
  "Contributed rule-negation support to an open source rules engine (json-rules-engine) powering an internal Node.js permissions service",
  "Developed internal tools for managing users, markets, and support tickets with TypeScript and React",
]

[[experiences]]
kind = "extracurricular"
name = "Software Developer"
context = "Sandbox at Northeastern University"
summary = "Northeastern's premier software consultancy."
url = "https://sandboxnu.com"
when = { Range = { start = 2020-09-01, end = 2021-05-01 } }
highlights = [
  "Developed features for a university course planning web application using Ruby on Rails, TypeScript, and React",
  "Wrote a Node.js parser to translate university course documentation PDFs into JSON for internal usage",
  "Provided technical mentoring to teammates on tasks through routine pair-programming",
  # "Modeled course schedule data in TypeScript, wrote logic for validating course requirements, and implemented React components to display interactive course plans to users"
]

[[experiences]]
kind = "work"
name = "Software Engineer Co-op"
context = "Teikametrics"
location = "Remote"
when = { Range = { start = 2020-01-01, end = 2020-08-01 } }
highlights = [
  "Wrote backend APIs in Scala and implemented UIs with TypeScript, React, and Redux to support Amazon ad campaign creation and display campaign performance metrics to users",
  # "Rapidly ramped up onto new technologies, progressing from no Scala, TypeScript, or web development experience to becoming an active contributor to a Scala with Cats backend and a TypeScript, React, and Redux frontend"
]

[[experiences]]
kind = "work"
name = "Software Engineer Co-op"
context = "Curriculum Associates"
location = { CityState = ["Billerica", "MA"] }
url = "https://curriculumassociates.com"
when = { Range = { start = 2019-01-14, end = 2019-06-20 } }
highlights = [
  "Updated SQL query templates in Java to retrieve language flags for student assessment data",
  "Drafted and implemented integration tests to ensure correct functionality of query templates",
  "Refactored database schemas with Liquibase and updated existing data for education platform privileges",
]

[[experiences]]
kind = "work"
name = "Grader for CS2500"
context = "Northeastern University College of Computer and Information Science"
location = { CityState = ["Boston", "MA"] }
when = { Range = { start = 2018-09-01, end = 2018-12-01 } }
highlights = [
  "Reviewed and graded roughly 30 student coding assignments per week written in Racket",
]

[[experiences]]
kind = "work"
name = "Technical Intern"
context = "Veoneer"
summary = "Manufacturer of automotive safety systems."
location = { CityState = ["Lowell", "MA"] }
url = "https://www.veoneer.com"
when = { Range = { start = 2018-05-29, end = 2018-08-10 } }
highlights = [
  "Ported over C++ implementation of target track positioner software to a new radar sensor testing suite written in C#",
  "Outlined architecture specifications for new radar units to lay groundwork for future sensor support within testing suite",
]

[[experiences]]
kind = "project"
name = "Bookmark Manager"
url = "https://github.com/andrewjleung/linkr"
when = { Year = 2023 }
tags = [
  "TypeScript",
  "Node.js",
  "React",
  "Next.js",
  "Tailwind",
  "shadcn/ui",
  "Supabase",
  "Drizzle ORM",
  "Jotai",
]
highlights = [
  "Created a self-hosted bookmark manager for personal use using TypeScript, React, Next.js, and shadcn/ui components",
  "Persisted bookmark data in a PostgreSQL database hosted by Supabase and queried with Drizzle ORM",
  "Restricted sign-in to a predefined user with GitHub OAuth and Supabase Auth",
  "Built a tool for importing and re-categorizing bookmarks from Raindrop.io",
]

[[experiences]]
kind = "project"
name = "Random Audio Player"
url = "https://github.com/andrewjleung/raudi"
when = { Year = 2022 }
tags = [
  "TypeScript",
  "Node.js",
  "Fastify",
  "React",
  "TailwindCSS",
  "NGINX",
  "Docker",
]

[[experiences]]
kind = "project"
name = "TheNeedleDrop Review Dataset"
url = "https://github.com/andrewjleung/fantano-reviews"
when = { Year = 2022 }
tags = ["TypeScript", "Node.js", "Fastify", "YouTube Data API", "PubSubHubBub"]
highlights = [
  "Implemented a Node.js script to fetch and parse metadata from the YouTube Data API in order to generate a CSV dataset of a popular music critic's video music reviews for use in data analysis",
  "Automated real-time updates to a hosted dataset using a PubSubHubBub server deployed to DigitalOcean via GitHub",
]

[[experiences]]
kind = "project"
name = "Compiler for Python-like Language"
when = { Year = 2022 }
tags = ["OCaml", "C", "x86 Assembly"]
highlights = [
  "Wrote an x86 compiler in OCaml and a C runtime for a Python-like expression-oriented language",
  "Supported dynamic types with integers, booleans, tuples, strings, and first-class functions",
  "Managed program memory with mark-and-sweep garbage collection and register allocation",
  "Wrote over 600 unit and E2E tests with OUnit to validate compiliation and language semantics",
]

[[experiences]]
kind = "project"
name = "Reze"
when = { Year = 2025 }
url = "https://github.com/andrewjleung/resumes"
tags = ["Rust", "Clap", "Serde", "Typst"]
highlights = [
  "Created a Rust CLI for rendering the JSON Resume standard into PDF with Typst with Clap",
  "Supported declarative filtering of CV content by date and title in code or TOML configuration",
  "Built a file-watcher for edits to resume content, supporting hot-reloading for PDF renders",
  "Configured a CI/CD pipeline with GitHub Actions to render and deploy resumes to GitHub Pages",
]

[[experiences]]
kind = "project"
name = "Ply"
summary = "a plaintext job application tracker"
when = { Year = 2025 }
url = "https://github.com/andrewjleung/ply"
tags = ["Rust", "Clap", "Serde", "Typst"]
highlights = [
  "Built a Rust CLI for tracking job application metadata/notes in TOML/Markdown using Clap and Serde",
  "Designed a framework to scrape/parse job listings over HTTP and generate job tracking documents",
  "Defined an API for declaring parsers for job boards in 5-6 lines of code with CSS selectors and regex",
]
