#:schema ./config.schema.json

artifact_title = "test"
output_dir = "./artifacts"
resume_data_path = "./resume.toml"

[typst]
template = "./template_v2.typ"

[work]
filters = [
  { After = 2021-01-01 },
  { Exclude = "Sandbox at Northeastern University" },
]
queries = [
  { After = 2021-01-01 },
  { Hide = "Sandbox at Northeastern University" },
]

[projects]
filters = [
  # { Include = "Compiler for Python-like Language" },
  { Include = "Ply" },
  { Include = "Reze" },
]
queries = [{ Show = "Ply" }, { Show = "Reze" }]
