#:schema ../../schemas/config.schema.json

title = "AndrewLeung_Resume"
output_dir = "./artifacts"
resume_data_path = "../../resume.toml"
template = "../../template.typ"
clean = true

[queries]
work = [
    { After = 2020-01-01 },
    { Hide = "Sandbox at Northeastern University" },
]
project = [
    { Show = "Compiler" },
    { Show = "Resume data and rendering manager" }
]
